Script started on 2015年03月10日 (週二) 20時51分17秒
]0;F74034091@2015cpp: ~F74034091@2015cpp:~$ whoami.[K;pwd
F74034091
/home/F74034091
]0;F74034091@2015cpp: ~F74034091@2015cpp:~$ git config --[Kl
]0;F74034091@2015cpp: ~F74034091@2015cpp:~$ got clone https://github.com/collin85820/lab1.git
No command 'got' found, did you mean:
 Command 'go' from package 'golang-go' (universe)
 Command 'gout' from package 'scotch' (universe)
 Command 'jot' from package 'athena-jot' (universe)
 Command 'git' from package 'git' (main)
 Command 'gpt' from package 'gpt' (universe)
 Command 'gom' from package 'gom' (universe)
 Command 'goo' from package 'goo' (universe)
 Command 'gst' from package 'gnu-smalltalk' (universe)
 Command 'dot' from package 'graphviz' (main)
 Command 'god' from package 'god' (universe)
got: command not found
]0;F74034091@2015cpp: ~F74034091@2015cpp:~$ git clone https://github.com/collin85820/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74034091@2015cpp: ~F74034091@2015cpp:~$ exit

Script done on 2015年03月10日 (週二) 20時52分21秒
